package com.gb.job.executor.core.mapper.gns;

import com.gb.job.executor.core.model.entity.gns.BetDetail;
import java.time.LocalDateTime;
import org.apache.ibatis.annotations.Param;

public interface BetDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("partnerData") String partnerData, @Param("timestamp") LocalDateTime timestamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    int insert(BetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    int insertSelective(BetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    BetDetail selectByPrimaryKey(@Param("partnerData") String partnerData, @Param("timestamp") LocalDateTime timestamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gns_bet_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BetDetail record);
}